export type {
    INormalizedPdfSearchRequest,
    INormalizedPdfSearchWarmIndexRequest,
    IPdfSearchExcerpt,
    IPdfSearchUtf16Range,
    IResolvedSearchMatchOptions,
    ISearchMatchOptions,
    TPdfSearchUtf16Offset,
} from '@contracts/search';

export {
    assertSafePdfSearchRegex,
    buildPdfSearchExcerpt,
    buildPdfSearchRegex,
    assembleSearchablePageText,
    collapseRepeatedPdfSearchPageText,
    escapeSearchRegex,
    findPdfSearchMatches,
    iteratePdfSearchMatches,
    mapAssembledSearchablePageTextRange,
    normalizeSearchText,
    normalizeOptionalSearchPageCount,
    normalizeOptionalSearchRequestId,
    normalizePdfSearchRequestPayload,
    normalizePdfSearchWarmIndexPayload,
    SEARCH_DOCUMENT_REVISION_TOKEN_MAX_LENGTH,
    SEARCH_PAGE_COUNT_DEFAULT_MAX,
    SEARCH_PDF_PATH_MAX_LENGTH,
    SEARCH_REQUEST_ID_MAX_LENGTH,
    SEARCH_QUERY_MAX_LENGTH as PDF_SEARCH_QUERY_MAX_LENGTH,
    SEARCH_REGEX_QUERY_MAX_LENGTH as PDF_SEARCH_REGEX_QUERY_MAX_LENGTH,
    validateSearchQuery,
} from '@contracts/search';
