export const ZOOM_VIEWPORT_ANCHOR_MAX_AGE_MS = 240;
export const WHEEL_ZOOM_GESTURE_GRACE_MS = 180;
export const WHEEL_ZOOM_SESSION_IDLE_MS = 220;
export const WHEEL_ZOOM_SESSION_LOCK_EXTENSION_MS = 260;
export const WHEEL_DETAIL_LOG_THROTTLE_MS = 320;
export const WHEEL_ZOOM_EXPECTED_SCROLL_WINDOW_MS = 1400;
