import type { IAgentCapabilityTemplate } from '@electron/features/agent/mcp/mcpDefinitionTypes';
import {
    ALLOW_INTERNAL_AND_EXTERNAL,
    ANNOTATION_COLOR_INPUT_SCHEMA,
    ANNOTATION_POINT_NOTE_INPUT_SCHEMA,
    ANNOTATION_REF_INPUT_SCHEMA,
    ANNOTATION_SHAPE_INPUT_SCHEMA,
    ANNOTATION_TEXT_MARKUP_INPUT_SCHEMA,
    ANNOTATION_TOOL_INPUT_SCHEMA,
    ANNOTATION_UPDATE_NOTE_INPUT_SCHEMA,
    BOOKMARK_ADD_BATCH_INPUT_SCHEMA,
    BOOKMARK_ADD_INPUT_SCHEMA,
    BOOKMARK_DELETE_BATCH_INPUT_SCHEMA,
    BOOKMARK_DELETE_INPUT_SCHEMA,
    BOOKMARK_PLAN_INPUT_SCHEMA,
    BOOKMARK_TREE_INPUT_SCHEMA,
    BOOKMARK_UPDATE_INPUT_SCHEMA,
    CAPTURE_PAGE_IMAGE_INPUT_SCHEMA,
    CONFIRM_ALL_WRITES,
    CONFIRM_EXTERNAL,
    EMPTY_INPUT_SCHEMA,
    INSERT_PAGES_INPUT_SCHEMA,
    OBJECT_OUTPUT_SCHEMA,
    OCR_RUN_INPUT_SCHEMA,
    OPEN_SIDEBAR_TAB_INPUT_SCHEMA,
    PAGE_INPUT_SCHEMA,
    PAGE_LABEL_APPLY_RANGE_INPUT_SCHEMA,
    PAGE_LABEL_PLAN_INPUT_SCHEMA,
    PAGE_LABEL_SET_LABELS_INPUT_SCHEMA,
    PAGE_LABEL_SET_RANGES_INPUT_SCHEMA,
    READ_PAGES_INPUT_SCHEMA,
    SEARCH_INPUT_SCHEMA,
    TAB_INPUT_SCHEMA,
    VIEW_MODE_INPUT_SCHEMA,
} from '@electron/features/agent/mcp/mcpCapabilitySchemas';

export const AGENT_CAPABILITY_TEMPLATES = [
    {
        id: 'workspace.snapshot',
        domain: 'workspace',
        title: 'Read workspace snapshot',
        summary: 'Read panes, tabs, active document, recent-file metadata, page numbers, and readiness hints.',
        risk: 'read',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'always',
        resourceTemplates: ['evb://workspace/current'],
    },
    {
        id: 'document.open_documents',
        domain: 'document',
        title: 'List open documents',
        summary: 'Read open EVB Viewer documents with active tab, page, dirty state, kind, and readiness.',
        risk: 'read',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'always',
    },
    {
        id: 'document.readiness',
        domain: 'document',
        title: 'Read document readiness',
        summary: 'Read document preparation hints for all tabs or a specific tab.',
        risk: 'read',
        inputSchema: TAB_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'always',
    },
    {
        id: 'document.inspect_text',
        domain: 'document',
        title: 'Inspect PDF text coverage',
        summary: 'Build or reuse EVB Viewer search index and report searchable text/OCR coverage by page.',
        risk: 'read',
        inputSchema: TAB_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'pdf-path',
        resourceTemplates: [
            'evb://document/{tabId}/text-status',
            'evb://document/{tabId}/ocr-status',
        ],
    },
    {
        id: 'document.search',
        domain: 'document',
        title: 'Search open PDF',
        summary: 'Search the open PDF using EVB Viewer cached search indexes and return page candidates with excerpts.',
        risk: 'read',
        inputSchema: SEARCH_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'pdf-path',
    },
    {
        id: 'document.read_pages',
        domain: 'document',
        title: 'Read PDF page text',
        summary: 'Read extracted searchable text for one or more one-based PDF pages.',
        risk: 'read',
        inputSchema: READ_PAGES_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'pdf-path',
        resourceTemplates: ['evb://document/{tabId}/page/{page}'],
    },
    {
        id: 'document.capture_page_image',
        domain: 'document',
        title: 'Capture rendered PDF page image',
        summary: 'Navigate/render a PDF page and return a PNG image of the full page or a normalized crop for visual verification when OCR/search/TOC evidence is uncertain.',
        risk: 'navigate',
        inputSchema: CAPTURE_PAGE_IMAGE_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-pdf',
    },
    {
        id: 'toc.read',
        domain: 'toc',
        title: 'Read TOC/bookmarks',
        summary: 'Read the active document table of contents/bookmarks when present.',
        risk: 'read',
        inputSchema: TAB_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
        resourceTemplates: ['evb://document/{tabId}/toc'],
    },
    {
        id: 'page_labels.read',
        domain: 'page_labels',
        title: 'Read page labels',
        summary: 'Read current PDF page numbering ranges, materialized labels, compact segments, samples, and validation hints.',
        risk: 'read',
        inputSchema: TAB_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
        resourceTemplates: ['evb://document/{tabId}/page-labels'],
    },
    {
        id: 'page_labels.preview',
        domain: 'page_labels',
        title: 'Preview page label plan',
        summary: 'Normalize proposed page-label ranges, inclusive segments, or explicit labels and return segments, samples, issues, and a changed-page diff without mutating the document.',
        risk: 'read',
        inputSchema: PAGE_LABEL_PLAN_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'page_labels.apply_plan',
        domain: 'page_labels',
        title: 'Apply page label plan',
        summary: 'Apply a verified page-label plan from ranges, inclusive segments, or explicit labels, returning the normalized snapshot and diff while recording an undoable metadata edit.',
        risk: 'write',
        inputSchema: PAGE_LABEL_PLAN_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'page_labels.set_ranges',
        domain: 'page_labels',
        title: 'Replace page label ranges',
        summary: 'Replace all PDF page numbering ranges in one batch.',
        risk: 'write',
        inputSchema: PAGE_LABEL_SET_RANGES_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'page_labels.apply_range',
        domain: 'page_labels',
        title: 'Apply page numbering range',
        summary: 'Apply decimal, roman, alphabetic, or literal numbering to one page range while preserving labels outside it.',
        risk: 'write',
        inputSchema: PAGE_LABEL_APPLY_RANGE_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'page_labels.set_labels',
        domain: 'page_labels',
        title: 'Set explicit page labels',
        summary: 'Set one or many explicit physical-page labels and derive compact numbering ranges from them.',
        risk: 'write',
        inputSchema: PAGE_LABEL_SET_LABELS_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'page_labels.clear',
        domain: 'page_labels',
        title: 'Reset page labels',
        summary: 'Reset page numbering to default physical decimal pages starting at 1.',
        risk: 'write',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'bookmarks.read',
        domain: 'bookmarks',
        title: 'Read bookmarks',
        summary: 'Read editable PDF bookmarks as a nested tree plus flat path-indexed entries, summary counts, and validation hints.',
        risk: 'read',
        inputSchema: TAB_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
        resourceTemplates: ['evb://document/{tabId}/bookmarks'],
    },
    {
        id: 'bookmarks.preview_tree',
        domain: 'bookmarks',
        title: 'Preview bookmark tree',
        summary: 'Normalize a proposed nested bookmark tree with items/children or flat TOC entries with level/depth values and return the nested tree, flat view, issues, and path-level diff without mutating the document.',
        risk: 'read',
        inputSchema: BOOKMARK_PLAN_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'bookmarks.apply_plan',
        domain: 'bookmarks',
        title: 'Apply bookmark plan',
        summary: 'Apply a verified nested bookmark tree with items/children or flat TOC-entry plan as an undoable metadata edit, returning the normalized tree, flat view, issues, and diff.',
        risk: 'write',
        inputSchema: BOOKMARK_PLAN_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'bookmarks.set_tree',
        domain: 'bookmarks',
        title: 'Replace bookmark tree',
        summary: 'Replace the full multi-level bookmark tree in one batch. Also accepts flat entries with level/depth values.',
        risk: 'write',
        inputSchema: BOOKMARK_TREE_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'bookmarks.add',
        domain: 'bookmarks',
        title: 'Add bookmark',
        summary: 'Add one bookmark at a root or child path, with optional style and nested children.',
        risk: 'write',
        inputSchema: BOOKMARK_ADD_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'bookmarks.add_batch',
        domain: 'bookmarks',
        title: 'Add bookmarks in batch',
        summary: 'Add multiple bookmarks, each optionally targeting a different parent path and insert index.',
        risk: 'write',
        inputSchema: BOOKMARK_ADD_BATCH_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'bookmarks.update',
        domain: 'bookmarks',
        title: 'Update bookmark',
        summary: 'Update one bookmark by zero-based tree path, including title, destination, style, color, or children.',
        risk: 'write',
        inputSchema: BOOKMARK_UPDATE_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'bookmarks.delete',
        domain: 'bookmarks',
        title: 'Delete bookmark',
        summary: 'Delete one bookmark subtree by zero-based tree path.',
        risk: 'destructive',
        inputSchema: BOOKMARK_DELETE_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_ALL_WRITES,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'bookmarks.delete_batch',
        domain: 'bookmarks',
        title: 'Delete bookmarks in batch',
        summary: 'Delete multiple bookmark subtrees by zero-based tree paths in one undoable metadata edit. Parent/child overlaps are collapsed so selected descendants are removed only once.',
        risk: 'destructive',
        inputSchema: BOOKMARK_DELETE_BATCH_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_ALL_WRITES,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'annotation.list',
        domain: 'annotation',
        title: 'Read annotations',
        summary: 'Read annotation summaries with stable keys, pages, subtype, color, and note flags.',
        risk: 'read',
        inputSchema: TAB_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
        resourceTemplates: ['evb://document/{tabId}/annotations'],
    },
    {
        id: 'annotation.list_notes',
        domain: 'annotation',
        title: 'Read notes',
        summary: 'Read note-bearing annotations and currently open note-window state.',
        risk: 'read',
        inputSchema: TAB_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
        resourceTemplates: ['evb://document/{tabId}/notes'],
    },
    {
        id: 'annotation.open_note',
        domain: 'annotation',
        title: 'Open annotation note',
        summary: 'Open the note popup/window for an annotation using a stable key from the annotations or notes resource.',
        risk: 'navigate',
        inputSchema: ANNOTATION_REF_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'annotation.focus',
        domain: 'annotation',
        title: 'Focus annotation',
        summary: 'Focus an annotation in the visible viewer using a stable key from the annotations resource.',
        risk: 'navigate',
        inputSchema: ANNOTATION_REF_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'annotation.update_note',
        domain: 'annotation',
        title: 'Update annotation note',
        summary: 'Replace the note text for an annotation using a stable key, annotation id, or id.',
        risk: 'write',
        inputSchema: ANNOTATION_UPDATE_NOTE_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'annotation.update_text_markup_color',
        domain: 'annotation',
        title: 'Update text markup color',
        summary: 'Apply a CSS color to an existing highlight, underline, strikethrough, or squiggly annotation.',
        risk: 'write',
        inputSchema: ANNOTATION_COLOR_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'annotation.create_note',
        domain: 'annotation',
        title: 'Start note creation',
        summary: 'Start EVB Viewer quick-note behavior for the current selection or page placement.',
        risk: 'write',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'annotation.create_note_at_point',
        domain: 'annotation',
        title: 'Create point note',
        summary: 'Create a page note at normalized PDF page coordinates, matching user quick-note placement.',
        risk: 'write',
        inputSchema: ANNOTATION_POINT_NOTE_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-pdf',
    },
    {
        id: 'annotation.create_text_markup',
        domain: 'annotation',
        title: 'Create text markup',
        summary: 'Create highlight, underline, strikethrough, or squiggly markup on matching visible PDF text by page and occurrence.',
        risk: 'write',
        inputSchema: ANNOTATION_TEXT_MARKUP_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-pdf',
    },
    {
        id: 'annotation.create_shape',
        domain: 'annotation',
        title: 'Create shape annotation',
        summary: 'Create rectangle, circle, line, arrow, or freehand draw annotations from normalized page geometry.',
        risk: 'write',
        inputSchema: ANNOTATION_SHAPE_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-pdf',
    },
    {
        id: 'annotation.select_tool',
        domain: 'annotation',
        title: 'Select annotation tool',
        summary: 'Select an annotation tool such as highlight, underline, text, draw, rectangle, circle, line, or arrow.',
        risk: 'write',
        inputSchema: ANNOTATION_TOOL_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'annotation.delete',
        domain: 'annotation',
        title: 'Delete annotation',
        summary: 'Delete an annotation/comment by stable key, annotation id, or id.',
        risk: 'destructive',
        inputSchema: ANNOTATION_REF_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_ALL_WRITES,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'ocr.open_popup',
        domain: 'ocr',
        title: 'Open OCR popup',
        summary: 'Open EVB Viewer OCR controls so OCR can be started with visible page/language options.',
        risk: 'navigate',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-pdf',
    },
    {
        id: 'ocr.status',
        domain: 'ocr',
        title: 'Read OCR popup status',
        summary: 'Read visible OCR popup state, selected page range, languages, quality profile, progress, errors, and running status.',
        risk: 'read',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'ocr.start',
        domain: 'ocr',
        title: 'Start OCR',
        summary: 'Start OCR for the target PDF using the current OCR settings or supplied page range, language codes, and quality profile.',
        risk: 'longRunning',
        inputSchema: OCR_RUN_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-pdf',
    },
    {
        id: 'ocr.cancel',
        domain: 'ocr',
        title: 'Cancel OCR',
        summary: 'Cancel the currently running OCR job for the target document when one is active.',
        risk: 'write',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'ui.open_sidebar_tab',
        domain: 'ui',
        title: 'Open sidebar tab',
        summary: 'Open a visible sidebar tab: annotations, bookmarks, thumbnails, or search.',
        risk: 'navigate',
        inputSchema: OPEN_SIDEBAR_TAB_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'ui.toggle_sidebar',
        domain: 'ui',
        title: 'Toggle sidebar',
        summary: 'Toggle the visible document sidebar.',
        risk: 'navigate',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'ui.close_popups',
        domain: 'ui',
        title: 'Close popups',
        summary: 'Close open EVB Viewer dropdowns and annotation property popups.',
        risk: 'navigate',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'view.activate_tab',
        domain: 'view',
        title: 'Activate tab',
        summary: 'Activate an open EVB Viewer tab by id.',
        risk: 'navigate',
        inputSchema: TAB_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'document',
    },
    {
        id: 'view.go_to_page',
        domain: 'view',
        title: 'Go to page',
        summary: 'Activate a tab if needed and navigate its PDF viewer to a one-based page number.',
        risk: 'navigate',
        inputSchema: PAGE_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-pdf',
    },
    {
        id: 'view.zoom_in',
        domain: 'view',
        title: 'Zoom in',
        summary: 'Increase visible zoom for the target document.',
        risk: 'navigate',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'view.zoom_out',
        domain: 'view',
        title: 'Zoom out',
        summary: 'Decrease visible zoom for the target document.',
        risk: 'navigate',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'view.fit_width',
        domain: 'view',
        title: 'Fit width',
        summary: 'Set the visible PDF fit mode to width.',
        risk: 'navigate',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'view.fit_height',
        domain: 'view',
        title: 'Fit height',
        summary: 'Set the visible PDF fit mode to height.',
        risk: 'navigate',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'view.actual_size',
        domain: 'view',
        title: 'Actual size',
        summary: 'Set the visible PDF zoom to 100%.',
        risk: 'navigate',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'view.toggle_continuous_scroll',
        domain: 'view',
        title: 'Toggle continuous scroll',
        summary: 'Toggle continuous scrolling for the target document.',
        risk: 'navigate',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'view.set_mode',
        domain: 'view',
        title: 'Set page view mode',
        summary: 'Set page view mode to single, facing, or facing-first-single.',
        risk: 'navigate',
        inputSchema: VIEW_MODE_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: ALLOW_INTERNAL_AND_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'file.save',
        domain: 'file',
        title: 'Save',
        summary: 'Save the current document when EVB Viewer reports it can be saved.',
        risk: 'write',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'file.save_as',
        domain: 'file',
        title: 'Save as',
        summary: 'Open Save As for the current document.',
        risk: 'write',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'file.print',
        domain: 'file',
        title: 'Print',
        summary: 'Open print for the current document.',
        risk: 'navigate',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'file.print_current_page',
        domain: 'file',
        title: 'Print current page',
        summary: 'Open print for the current page.',
        risk: 'navigate',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'export.docx',
        domain: 'export',
        title: 'Export DOCX',
        summary: 'Start DOCX export for the current document.',
        risk: 'longRunning',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'export.images',
        domain: 'export',
        title: 'Export images',
        summary: 'Open image export for the current document.',
        risk: 'longRunning',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'export.multi_page_tiff',
        domain: 'export',
        title: 'Export multi-page TIFF',
        summary: 'Open multi-page TIFF export for the current document.',
        risk: 'longRunning',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-document',
    },
    {
        id: 'page_ops.delete_selected',
        domain: 'page_ops',
        title: 'Delete selected pages',
        summary: 'Delete pages currently selected in the thumbnails sidebar.',
        risk: 'destructive',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_ALL_WRITES,
        availabilityKind: 'renderer-pdf',
    },
    {
        id: 'page_ops.extract_selected',
        domain: 'page_ops',
        title: 'Extract selected pages',
        summary: 'Extract pages currently selected in the thumbnails sidebar.',
        risk: 'write',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-pdf',
    },
    {
        id: 'page_ops.rotate_cw_selected',
        domain: 'page_ops',
        title: 'Rotate selected pages clockwise',
        summary: 'Rotate currently selected thumbnail pages clockwise.',
        risk: 'write',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-pdf',
    },
    {
        id: 'page_ops.rotate_ccw_selected',
        domain: 'page_ops',
        title: 'Rotate selected pages counterclockwise',
        summary: 'Rotate currently selected thumbnail pages counterclockwise.',
        risk: 'write',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-pdf',
    },
    {
        id: 'page_ops.insert_pages',
        domain: 'page_ops',
        title: 'Insert pages',
        summary: 'Open page insertion for the current document.',
        risk: 'write',
        inputSchema: INSERT_PAGES_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'renderer-pdf',
    },
    {
        id: 'page_ops.convert_to_pdf',
        domain: 'page_ops',
        title: 'Convert to PDF',
        summary: 'Open conversion flow for DjVu/image documents or the file open flow for PDF conversion.',
        risk: 'longRunning',
        inputSchema: EMPTY_INPUT_SCHEMA,
        outputSchema: OBJECT_OUTPUT_SCHEMA,
        policy: CONFIRM_EXTERNAL,
        availabilityKind: 'document',
    },
] as const satisfies readonly IAgentCapabilityTemplate[];
