use crate::Result;

pub(crate) struct NetpbmData<'a> {
    pub(crate) width: u32,
    pub(crate) height: u32,
    pub(crate) channels: u8,
    pub(crate) pixels: &'a [u8],
}

pub(crate) fn parse_netpbm(data: &[u8]) -> Result<NetpbmData<'_>> {
    if data.len() < 4 {
        return Err("Netpbm payload is too short".into());
    }

    let channels = match data.get(0..2) {
        Some(b"P5") => 1,
        Some(b"P6") => 3,
        _ => return Err("Unsupported Netpbm format".into()),
    };

    let mut offset = 2usize;
    let width = read_netpbm_number(data, &mut offset, "width")?;
    let height = read_netpbm_number(data, &mut offset, "height")?;
    let maxval = read_netpbm_number(data, &mut offset, "maxval")?;
    if maxval == 0 || maxval > 255 {
        return Err(format!("Unsupported maxval {maxval} (only 8-bit supported)").into());
    }
    if offset >= data.len() || !is_whitespace_byte(data[offset]) {
        return Err("Invalid Netpbm header terminator".into());
    }
    offset += 1;

    let data_size = (width as usize)
        .checked_mul(height as usize)
        .and_then(|value| value.checked_mul(channels as usize))
        .ok_or("Invalid Netpbm payload size")?;
    let data_end = offset
        .checked_add(data_size)
        .ok_or("Invalid Netpbm payload size")?;
    let pixels = data
        .get(offset..data_end)
        .ok_or("Truncated Netpbm payload")?;

    Ok(NetpbmData {
        width,
        height,
        channels,
        pixels,
    })
}

fn read_netpbm_number(data: &[u8], offset: &mut usize, label: &str) -> Result<u32> {
    skip_netpbm_whitespace_and_comments(data, offset);
    if *offset >= data.len() {
        return Err(format!("Missing {label} in Netpbm header").into());
    }

    let start = *offset;
    while *offset < data.len() && data[*offset].is_ascii_digit() {
        *offset += 1;
    }
    if start == *offset {
        return Err(format!("Invalid {label} in Netpbm header").into());
    }

    let value = std::str::from_utf8(&data[start..*offset])?.parse::<u32>()?;
    if value == 0 {
        return Err(format!("Invalid {label} in Netpbm header").into());
    }
    Ok(value)
}

fn skip_netpbm_whitespace_and_comments(data: &[u8], offset: &mut usize) {
    while *offset < data.len() {
        let byte = data[*offset];
        if byte == b'#' {
            while *offset < data.len() && data[*offset] != b'\n' {
                *offset += 1;
            }
            if *offset < data.len() {
                *offset += 1;
            }
            continue;
        }
        if is_whitespace_byte(byte) {
            *offset += 1;
            continue;
        }
        break;
    }
}

fn is_whitespace_byte(byte: u8) -> bool {
    matches!(byte, b' ' | b'\t' | b'\n' | b'\r')
}

pub(crate) fn is_rgb_data_grayscale(pixels: &[u8], total_pixels: usize) -> bool {
    let step = std::cmp::max(1, total_pixels / 10_000);
    for index in (0..total_pixels).step_by(step) {
        let offset = index * 3;
        if pixels[offset] != pixels[offset + 1] || pixels[offset] != pixels[offset + 2] {
            return false;
        }
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_netpbm_comments_and_payload() {
        let data = b"P6\n# generated by ddjvu\n2 1\n255\n\x01\x01\x01\x02\x03\x04";
        let netpbm = parse_netpbm(data).unwrap();

        assert_eq!(netpbm.width, 2);
        assert_eq!(netpbm.height, 1);
        assert_eq!(netpbm.channels, 3);
        assert_eq!(netpbm.pixels, &[1, 1, 1, 2, 3, 4]);
    }
}
