use crate::Result;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PbmP4Image {
    pub width: u32,
    pub height: u32,
    pub row_stride: usize,
    /// Raw PBM P4 rows. A 1 bit is foreground and is painted black by the PDF mask writer.
    pub bitmap: Vec<u8>,
}

pub(crate) struct NetpbmData<'a> {
    pub(crate) width: u32,
    pub(crate) height: u32,
    pub(crate) channels: u8,
    pub(crate) pixels: &'a [u8],
}

pub fn parse_pbm_p4(data: &[u8]) -> Result<PbmP4Image> {
    if data.len() < 4 {
        return Err("PBM P4 payload is too short".into());
    }
    if data.get(0..2) != Some(b"P4") {
        return Err("Unsupported PBM format".into());
    }

    let mut offset = 2usize;
    let width = read_netpbm_number(data, &mut offset, "width")?;
    let height = read_netpbm_number(data, &mut offset, "height")?;
    consume_netpbm_header_terminator(data, &mut offset, "PBM P4")?;

    let row_stride = (width as usize)
        .checked_add(7)
        .ok_or("Invalid PBM P4 row stride")?
        / 8;
    let data_size = row_stride
        .checked_mul(height as usize)
        .ok_or("Invalid PBM P4 payload size")?;
    let data_end = offset
        .checked_add(data_size)
        .ok_or("Invalid PBM P4 payload size")?;
    let bitmap = data
        .get(offset..data_end)
        .ok_or("Truncated PBM P4 payload")?
        .to_vec();

    Ok(PbmP4Image {
        width,
        height,
        row_stride,
        bitmap,
    })
}

pub(crate) fn parse_netpbm(data: &[u8]) -> Result<NetpbmData<'_>> {
    if data.len() < 4 {
        return Err("Netpbm payload is too short".into());
    }

    let channels = match data.get(0..2) {
        Some(b"P5") => 1,
        Some(b"P6") => 3,
        _ => return Err("Unsupported Netpbm format".into()),
    };

    let mut offset = 2usize;
    let width = read_netpbm_number(data, &mut offset, "width")?;
    let height = read_netpbm_number(data, &mut offset, "height")?;
    let maxval = read_netpbm_number(data, &mut offset, "maxval")?;
    if maxval != 255 {
        return Err(format!("Unsupported maxval {maxval} (only maxval 255 is supported)").into());
    }
    consume_netpbm_header_terminator(data, &mut offset, "Netpbm")?;

    let data_size = (width as usize)
        .checked_mul(height as usize)
        .and_then(|value| value.checked_mul(channels as usize))
        .ok_or("Invalid Netpbm payload size")?;
    let data_end = offset
        .checked_add(data_size)
        .ok_or("Invalid Netpbm payload size")?;
    let pixels = data
        .get(offset..data_end)
        .ok_or("Truncated Netpbm payload")?;

    Ok(NetpbmData {
        width,
        height,
        channels,
        pixels,
    })
}

fn read_netpbm_number(data: &[u8], offset: &mut usize, label: &str) -> Result<u32> {
    skip_netpbm_whitespace_and_comments(data, offset);
    if *offset >= data.len() {
        return Err(format!("Missing {label} in Netpbm header").into());
    }

    let start = *offset;
    while *offset < data.len() && data[*offset].is_ascii_digit() {
        *offset += 1;
    }
    if start == *offset {
        return Err(format!("Invalid {label} in Netpbm header").into());
    }

    let value = std::str::from_utf8(&data[start..*offset])?.parse::<u32>()?;
    if value == 0 {
        return Err(format!("Invalid {label} in Netpbm header").into());
    }
    Ok(value)
}

fn skip_netpbm_whitespace_and_comments(data: &[u8], offset: &mut usize) {
    while *offset < data.len() {
        let byte = data[*offset];
        if byte == b'#' {
            while *offset < data.len() && data[*offset] != b'\n' {
                *offset += 1;
            }
            if *offset < data.len() {
                *offset += 1;
            }
            continue;
        }
        if is_whitespace_byte(byte) {
            *offset += 1;
            continue;
        }
        break;
    }
}

fn consume_netpbm_header_terminator(data: &[u8], offset: &mut usize, label: &str) -> Result<()> {
    if *offset >= data.len() || !is_whitespace_byte(data[*offset]) {
        return Err(format!("Invalid {label} header terminator").into());
    }
    if data[*offset] == b'\r' && data.get(*offset + 1) == Some(&b'\n') {
        *offset += 2;
    } else {
        *offset += 1;
    }
    Ok(())
}

fn is_whitespace_byte(byte: u8) -> bool {
    matches!(byte, b' ' | b'\t' | b'\n' | b'\r')
}

pub(crate) fn is_rgb_data_grayscale(pixels: &[u8], total_pixels: usize) -> bool {
    let Some(expected_len) = total_pixels.checked_mul(3) else {
        return false;
    };
    let Some(pixels) = pixels.get(..expected_len) else {
        return false;
    };

    pixels
        .chunks_exact(3)
        .all(|pixel| pixel[0] == pixel[1] && pixel[0] == pixel[2])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_netpbm_comments_and_payload() {
        let data = b"P6\n# generated by ddjvu\n2 1\n255\n\x01\x01\x01\x02\x03\x04";
        let netpbm = parse_netpbm(data).unwrap();

        assert_eq!(netpbm.width, 2);
        assert_eq!(netpbm.height, 1);
        assert_eq!(netpbm.channels, 3);
        assert_eq!(netpbm.pixels, &[1, 1, 1, 2, 3, 4]);
    }

    #[test]
    fn rejects_netpbm_maxval_below_255() {
        let result = parse_netpbm(b"P5\n1 1\n15\n\x0f");

        assert!(result.is_err());
    }

    #[test]
    fn parses_pbm_p4_comments_whitespace_and_row_stride() {
        let data = b"P4\n# generated by ddjvu\n10\t2\r\n\x80\x7f\xff\xaa";
        let mask = parse_pbm_p4(data).unwrap();

        assert_eq!(mask.width, 10);
        assert_eq!(mask.height, 2);
        assert_eq!(mask.row_stride, 2);
        assert_eq!(mask.bitmap, vec![0x80, 0x7f, 0xff, 0xaa]);
    }

    #[test]
    fn preserves_pbm_p4_padding_bits_for_mask_polarity() {
        let mask = parse_pbm_p4(b"P4\n3 1\n\xe0").unwrap();

        assert_eq!(mask.row_stride, 1);
        assert_eq!(mask.bitmap, vec![0b1110_0000]);
    }

    #[test]
    fn rejects_malformed_pbm_p4_input() {
        assert!(parse_pbm_p4(b"P1\n1 1\n\x80").is_err());
        assert!(parse_pbm_p4(b"P4\n1 1\x80").is_err());
    }

    #[test]
    fn rejects_truncated_pbm_p4_payload() {
        let result = parse_pbm_p4(b"P4\n9 2\n\x80\x00\xff");

        assert!(result.is_err());
    }

    #[test]
    fn detects_sparse_rgb_color() {
        let total_pixels = 20_000usize;
        let mut pixels = vec![7u8; total_pixels * 3];
        let sparse_color_offset = 1usize * 3;
        pixels[sparse_color_offset + 1] = 8;

        assert!(!is_rgb_data_grayscale(&pixels, total_pixels));
    }
}
