export const DOCUMENTS_CHANNELS = {
    openPdfDialog: 'dialog:openPdf',
    openCombineDialog: 'dialog:openCombine',
    openFolderDialog: 'dialog:openFolder',
    openImageDialog: 'dialog:openImage',
    openPdfDirect: 'dialog:openPdfDirect',
    openPdfDirectBatch: 'dialog:openPdfDirectBatch',
    registerRendererFileOpenToken: 'dialog:registerRendererFileOpenToken',
    allowRendererFileOpen: 'dialog:allowRendererFileOpen',
    createWorkingCopyFromData: 'working-copy:createFromData',
    createWorkingCopyFromPath: 'working-copy:createFromPath',
    savePdfAs: 'dialog:savePdfAs',
    savePdfDialog: 'dialog:savePdfDialog',
    saveDocxAs: 'dialog:saveDocxAs',
    fileRead: 'file:read',
    fileStat: 'file:stat',
    fileReadRange: 'file:readRange',
    fileReadText: 'file:readText',
    fileExists: 'file:exists',
    pdfAnalyzeConformance: 'pdf:analyzeConformance',
    pdfValidateData: 'pdf:validateData',
    pdfOpenInDefaultAppData: 'pdf:openInDefaultAppData',
    pdfOpenInDefaultAppPath: 'pdf:openInDefaultAppPath',
    pdfPrintData: 'pdf:printData',
    pdfPrintPath: 'pdf:printPath',
    fileWrite: 'file:write',
    fileWriteDocx: 'file:writeDocx',
    fileSave: 'file:save',
    fileCleanup: 'file:cleanup',
    fileCleanupOcrTemp: 'file:cleanupOcrTemp',
    windowSetTitle: 'window:setTitle',
    shellShowItemInFolder: 'shell:showItemInFolder',
    menuSetDocumentState: 'menu:setDocumentState',
    menuSetTabCount: 'menu:setTabCount',
    recentFilesGet: 'recent-files:get',
    recentFilesRemove: 'recent-files:remove',
    recentFilesClear: 'recent-files:clear',
} as const;

export const DOCUMENTS_EVENT_CHANNELS = {
    menuOpenPdf: 'menu:openPdf',
    menuInsertImageFromFile: 'menu:insertImageFromFile',
    menuPasteImageFromClipboard: 'menu:pasteImageFromClipboard',
    menuSave: 'menu:save',
    menuSaveAs: 'menu:saveAs',
    menuPrint: 'menu:print',
    menuPrintCurrentPage: 'menu:printCurrentPage',
    menuExportDocx: 'menu:exportDocx',
    menuExportImages: 'menu:exportImages',
    menuExportMultiPageTiff: 'menu:exportMultiPageTiff',
    menuZoomIn: 'menu:zoomIn',
    menuZoomOut: 'menu:zoomOut',
    menuActualSize: 'menu:actualSize',
    menuFitWidth: 'menu:fitWidth',
    menuFitHeight: 'menu:fitHeight',
    menuViewModeSingle: 'menu:viewModeSingle',
    menuViewModeFacing: 'menu:viewModeFacing',
    menuViewModeFacingFirstSingle: 'menu:viewModeFacingFirstSingle',
    menuUndo: 'menu:undo',
    menuRedo: 'menu:redo',
    menuDeletePages: 'menu:deletePages',
    menuExtractPages: 'menu:extractPages',
    menuRotateCw: 'menu:rotateCw',
    menuRotateCcw: 'menu:rotateCcw',
    menuInsertPages: 'menu:insertPages',
    menuOpenRecentFile: 'menu:openRecentFile',
    menuOpenExternalPaths: 'menu:openExternalPaths',
    menuClearRecentFiles: 'menu:clearRecentFiles',
    openPdfDirectBatchProgress: 'dialog:openPdfDirectBatch:progress',
} as const;

export type TDocumentsEventChannels = typeof DOCUMENTS_EVENT_CHANNELS;

export type { TOpenFileResult } from '@contracts/electron-api-documents';
