import type { IPdfViewerExpose } from '@app/modules/pdf-viewer/runtime/contracts/pdfViewerExpose.types';

export const requiredPdfViewerExposeMembers = [
    'getViewerContainer',
    'getPagePreview',
    'getCurrentPage',
    'getPendingNavigationTargetPage',
    'scrollToPage',
    'cancelProgrammaticNavigation',
    'captureScrollSnapshot',
    'restoreScrollSnapshot',
    'preserveNextSourceReloadVisibleContent',
    'applyFitWidthToCurrentPage',
    'waitForViewerLoadSettled',
    'ensurePageMetricsInRange',
    'getPageMetricsSnapshot',
    'captureRegionToClipboard',
    'isCapturingRegion',
    'startCropSelection',
    'cancelCropSelection',
    'isCropSelecting',
    'adoptPersistedManagedShapesOnNextImport',
    'clearPendingManagedShapeImportAdoption',
    'preparePersistedManagedShapesForSave',
    'restorePreparedManagedShapesAfterFailedSave',
    'saveDocument',
    'commitPdfEditorsForSave',
    'clearAnnotationHistory',
    'renderLoadedPdfPagesForBrowserPrint',
    'highlightSelection',
    'commentSelection',
    'createTextMarkupFromText',
    'commentAtPoint',
    'createPointNoteAnnotation',
    'createShapeAnnotation',
    'startCommentPlacement',
    'cancelCommentPlacement',
    'undoAnnotation',
    'redoAnnotation',
    'registerAnnotationHistoryCommand',
    'focusAnnotationComment',
    'updateAnnotationComment',
    'deleteAnnotationComment',
    'getAnnotationCommentsSnapshot',
    'suppressAnnotationId',
    'unsuppressAnnotationId',
    'suppressAnnotationStableKey',
    'unsuppressAnnotationStableKey',
    'removeAnnotationFromDom',
    'removeAnnotationFromInternalCache',
    'restoreAnnotationToInternalCache',
    'clearPendingMarkerMoves',
    'getMarkupSubtypeOverrides',
    'getMarkupSubtypeHints',
    'getSelectedTextMarkupAnnotationProperties',
    'updateSelectedTextMarkupAnnotationColor',
    'updateTextMarkupAnnotationColor',
    'getAllShapes',
    'markSavedShapeState',
    'getDeletedEmbeddedShapeAnnotationIds',
    'getDeletedEmbeddedShapeStableKeys',
    'loadShapes',
    'clearShapes',
    'clearSelectedShape',
    'deleteSelectedShape',
    'hasShapes',
    'selectedShapeId',
    'updateShape',
    'getSelectedShape',
    'startImagePlacement',
    'clearPendingImagePlacement',
    'restorePendingImagePlacement',
    'invalidatePages',
    'requestScrollToCurrentResult',
] as const satisfies ReadonlyArray<keyof IPdfViewerExpose>;

type TPdfViewerExposeListedMember = typeof requiredPdfViewerExposeMembers[number];
type TMissingPdfViewerExposeMember = Exclude<keyof IPdfViewerExpose, TPdfViewerExposeListedMember>;
type TUnexpectedPdfViewerExposeMember = Exclude<TPdfViewerExposeListedMember, keyof IPdfViewerExpose>;

const pdfViewerExposeMemberSyncCheck: Record<
    TMissingPdfViewerExposeMember | TUnexpectedPdfViewerExposeMember,
    never
> = {};
void pdfViewerExposeMemberSyncCheck;
