export const SEARCH_DEBOUNCE_MS = 0;

export const FOCUS_PULSE_MS = 900;

export const OCR_TIMEOUT_MS = 30 * 60 * 1000;

export const ANNOTATION_NOTE_SAVE_DEBOUNCE_MS = 220;

export const SELECTION_CACHE_TTL_MS = 3000;

export const PDF_PAGE_LOAD_TIMEOUT_MS = 12_000;

export const PDF_PAGE_RENDER_TIMEOUT_MS = 15_000;

export const PDF_PAGE_STALL_RECOVERY_COOLDOWN_MS = 20_000;

export const PDF_SAVE_TIMEOUT_MS = 15_000;
