export const SEARCH_DEBOUNCE_MS = 0;

export const FOCUS_PULSE_MS = 900;

export const OCR_TIMEOUT_MS = 30 * 60 * 1000;

export const ANNOTATION_NOTE_SAVE_DEBOUNCE_MS = 220;

export const SELECTION_CACHE_TTL_MS = 3000;

export const PDF_PAGE_RENDER_TIMEOUT_MS = 15_000;

export const PDF_PAGE_TEXT_LAYER_TIMEOUT_MS = 15_000;

export const PDF_RESIZE_RERENDER_DEBOUNCE_MS = 200;

export const PDF_RESIZE_TRANSITION_HIDE_MS = 90;

export const PDF_RESIZE_DRAG_SETTLE_MS = 20;

export const PDF_RESIZE_DEFERRED_BEHIND_ZOOM_MAX_MS = 1_500;


export const PDF_SAVE_TIMEOUT_MS = 15_000;
