export const DB_NAME = 'evb-viewer-browser-documents';
export const DB_VERSION = 2;
export const DOCUMENTS_STORE = 'documents';
export const DOCUMENT_CHUNKS_STORE = 'document-chunks';
export const BROWSER_DOCUMENT_CHUNK_SIZE = 4 * 1024 * 1024;
export const BROWSER_MAX_FULL_READ_BYTES = 64 * 1024 * 1024;
export const BROWSER_MAX_RECENT_FILES = 30;
export const BROWSER_MAX_RECENT_FILES_PERSISTED_BYTES = 512 * 1024 * 1024;
export const BROWSER_CHUNK_WRITE_YIELD_EVERY = 2;
