import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
    GENERATED_RUST_NATIVE_TOOL_PROTOCOLS,
    type IGeneratedRustNativeToolProtocol,
} from '@contracts/nativeToolProtocols';
import { writeGeneratedFileIfChanged } from '@scripts/writeGeneratedFileIfChanged';

export interface IGenerateNativeToolProtocolsOptions {
    projectRoot?: string;
    protocols?: readonly IGeneratedRustNativeToolProtocol[];
}

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const generatedRustRelativePath = 'native/evb-native-support/src/generated_native_tool_protocols.rs';

function rustConstantName(protocol: IGeneratedRustNativeToolProtocol) {
    return protocol.stagingName.replaceAll('-', '_').toUpperCase();
}

export function renderRustNativeToolProtocols(
    protocols: readonly IGeneratedRustNativeToolProtocol[] = GENERATED_RUST_NATIVE_TOOL_PROTOCOLS,
) {
    const constants = protocols.map((protocol) => {
        const name = rustConstantName(protocol);
        const constructor = `NativeToolDescriptor::new(${JSON.stringify(protocol.binaryName)}, ${protocol.protocolVersion});`;
        const declaration = `pub const ${name}: NativeToolDescriptor = ${constructor}`;
        return declaration.length <= 100
            ? declaration
            : `pub const ${name}: NativeToolDescriptor =\n    ${constructor}`;
    }).join('\n\n');
    const allDescriptors = protocols.map(rustConstantName).join(', ');

    return `// Generated by scripts/generateNativeToolProtocols.ts. Do not edit.\n\nuse crate::NativeToolDescriptor;\n\n${constants}\n\npub const ALL_NATIVE_TOOL_DESCRIPTORS: &[NativeToolDescriptor] =\n    &[${allDescriptors}];\n`;
}

export async function generateNativeToolProtocols(
    options: IGenerateNativeToolProtocolsOptions = {},
) {
    const root = options.projectRoot ?? projectRoot;
    const protocols = options.protocols ?? GENERATED_RUST_NATIVE_TOOL_PROTOCOLS;
    return writeGeneratedFileIfChanged(
        path.join(root, generatedRustRelativePath),
        renderRustNativeToolProtocols(protocols),
    );
}

const isDirectCliRun = process.argv[1] !== undefined
    && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));

if (isDirectCliRun) {
    try {
        if (process.argv.length > 2) {
            throw new Error('Usage: node --import tsx scripts/generateNativeToolProtocols.ts');
        }
        const changed = await generateNativeToolProtocols();
        if (changed) {
            console.info('Generated native tool protocol artifacts.');
        }
    } catch (error) {
        console.error(error instanceof Error ? error.message : String(error));
        process.exitCode = 1;
    }
}
