import {
    mkdir,
    readFile,
    readdir,
    writeFile,
} from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
    AVAILABLE_OCR_LANGUAGES,
    BUNDLED_OCR_LANGUAGE_CODES,
} from '@contracts/ocrLanguages';
import {
    NATIVE_TOOL_RESOURCE_FAMILIES,
    type INativeToolResourceFamily,
    type TNativeResourcePlatform,
} from '@scripts/nativeResourceManifest';

export interface IElectronBuilderResourcePlan {
    content: string;
    relativePath: string;
}

export interface IGenerateElectronBuilderResourcesOptions { projectRoot?: string; }

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const generatedRelativePath = '.tmp/generated-electron-builder-resources.yml';
const tessdataRelativePath = 'resources/tesseract/tessdata';

function platformTag(platform: TNativeResourcePlatform) {
    return `${platform}-\${arch}`;
}

function renderNativeResource(
    family: INativeToolResourceFamily,
    platform: TNativeResourcePlatform,
) {
    const lines = [
        `    - from: ${path.posix.join(...family.sourceRootSegments, platformTag(platform))}`,
        `      to: ${path.posix.join(...family.stagedRootSegments, platformTag(platform))}`,
    ];
    if (family.id === 'poppler' && platform === 'win32') {
        lines.push(
            '      filter:',
            '        - "**/*"',
            '        - "!share/poppler/CMakeLists.txt"',
            '        - "!share/poppler/Makefile"',
            '        - "!share/poppler/README"',
            '        - "!share/poppler/poppler-data.pc"',
            '        - "!share/poppler/poppler-data.pc.in"',
        );
    }
    return lines.join('\n');
}

export function renderElectronBuilderResources(
    bundledOcrCodes: readonly string[] = BUNDLED_OCR_LANGUAGE_CODES,
    nativeResourceFamilies: readonly INativeToolResourceFamily[] = NATIVE_TOOL_RESOURCE_FAMILIES,
) {
    const rootResources = [
        'extraResources:',
        '  - from: resources/tesseract/tessdata',
        '    to: tesseract/tessdata',
        '    filter:',
        ...bundledOcrCodes.map(code => `      - ${code}.traineddata`),
        '  - from: resources/icon.png',
        '    to: icon.png',
    ].join('\n');
    const platformResources = ([
        [
            'mac',
            'darwin',
        ],
        [
            'win',
            'win32',
        ],
        [
            'linux',
            'linux',
        ],
    ] as const).map(([
        configKey,
        platform,
    ]) => [
        `${configKey}:`,
        '  extraResources:',
        ...nativeResourceFamilies.map(family => renderNativeResource(family, platform)),
    ].join('\n')).join('\n\n');

    return [
        '# Generated by scripts/generateElectronBuilderResources.ts. Do not edit.',
        '',
        rootResources,
        '',
        platformResources,
        '',
    ].join('\n');
}

async function assertOcrRegistryMatchesResources(root: string) {
    const registryCodes: string[] = AVAILABLE_OCR_LANGUAGES
        .map(language => language.code)
        .sort();
    const tessdataDirectory = path.join(root, tessdataRelativePath);
    const tessdataCodes = (await readdir(tessdataDirectory, {withFileTypes: true}))
        .filter(entry => entry.isFile() && entry.name.endsWith('.traineddata'))
        .map(entry => entry.name.slice(0, -'.traineddata'.length))
        .sort();
    const bundledCodes = [...BUNDLED_OCR_LANGUAGE_CODES].sort();
    const missingModels = registryCodes.filter(code => !tessdataCodes.includes(code));
    const unregisteredModels = tessdataCodes.filter(code => !registryCodes.includes(code));
    const invalidBundledModels = bundledCodes.filter(code => !tessdataCodes.includes(code));

    if (missingModels.length > 0 || unregisteredModels.length > 0 || invalidBundledModels.length > 0) {
        throw new Error([
            'OCR registry and tessdata_best resources are out of sync.',
            `Missing traineddata: ${missingModels.join(', ') || '(none)'}`,
            `Unregistered traineddata: ${unregisteredModels.join(', ') || '(none)'}`,
            `Invalid bundled defaults: ${invalidBundledModels.join(', ') || '(none)'}`,
        ].join('\n'));
    }
}

export async function createElectronBuilderResourcePlan(
    options: IGenerateElectronBuilderResourcesOptions = {},
): Promise<IElectronBuilderResourcePlan> {
    const root = options.projectRoot ?? projectRoot;
    await assertOcrRegistryMatchesResources(root);
    return {
        content: renderElectronBuilderResources(),
        relativePath: generatedRelativePath,
    };
}

export async function generateElectronBuilderResources(
    options: IGenerateElectronBuilderResourcesOptions = {},
) {
    const root = options.projectRoot ?? projectRoot;
    const plan = await createElectronBuilderResourcePlan({projectRoot: root});
    const outputPath = path.join(root, plan.relativePath);
    const current = await readFile(outputPath, 'utf8').catch(() => null);
    if (current === plan.content) {
        return false;
    }
    await mkdir(path.dirname(outputPath), {recursive: true});
    await writeFile(outputPath, plan.content, 'utf8');
    return true;
}

const isDirectCliRun = process.argv[1] !== undefined
    && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));

if (isDirectCliRun && await generateElectronBuilderResources()) {
    console.info('Generated Electron Builder resource manifest.');
}
