import {
    mkdir,
    readFile,
    writeFile,
} from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
    GENERATED_RUST_NATIVE_TOOL_PROTOCOLS,
    type IGeneratedRustNativeToolProtocol,
} from '@contracts/nativeToolProtocols';

export interface IGenerateNativeToolProtocolsOptions {
    check?: boolean;
    projectRoot?: string;
    protocols?: readonly IGeneratedRustNativeToolProtocol[];
}

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const generatedRustRelativePath = 'native/evb-native-support/src/generated_native_tool_protocols.rs';
const generatedReleaseRelativePath = 'scripts/release/generated-native-tool-protocols.mjs';

function rustConstantName(protocol: IGeneratedRustNativeToolProtocol) {
    return protocol.stagingName.replaceAll('-', '_').toUpperCase();
}

function javascriptString(value: string) {
    return `'${value.replaceAll('\\', '\\\\').replaceAll('\'', '\\\'')}'`;
}

export function renderRustNativeToolProtocols(
    protocols: readonly IGeneratedRustNativeToolProtocol[] = GENERATED_RUST_NATIVE_TOOL_PROTOCOLS,
) {
    const constants = protocols.map((protocol) => {
        const name = rustConstantName(protocol);
        const constructor = `NativeToolDescriptor::new(${JSON.stringify(protocol.binaryName)}, ${protocol.protocolVersion});`;
        const declaration = `pub const ${name}: NativeToolDescriptor = ${constructor}`;
        return declaration.length <= 100
            ? declaration
            : `pub const ${name}: NativeToolDescriptor =\n    ${constructor}`;
    }).join('\n\n');
    const allDescriptors = protocols.map(rustConstantName).join(', ');

    return `// Generated by scripts/generateNativeToolProtocols.ts. Do not edit.\n\nuse crate::NativeToolDescriptor;\n\n${constants}\n\npub const ALL_NATIVE_TOOL_DESCRIPTORS: &[NativeToolDescriptor] =\n    &[${allDescriptors}];\n`;
}

export function renderReleaseNativeToolProtocols(
    protocols: readonly IGeneratedRustNativeToolProtocol[] = GENERATED_RUST_NATIVE_TOOL_PROTOCOLS,
) {
    const descriptors = protocols.map(protocol => [
        '    Object.freeze({',
        `        binaryName: ${javascriptString(protocol.binaryName)},`,
        `        protocolVersion: ${protocol.protocolVersion},`,
        '    }),',
    ].join('\n')).join('\n');

    return `// Generated by scripts/generateNativeToolProtocols.ts. Do not edit.\n\nexport const GENERATED_RELEASE_NATIVE_TOOL_PROTOCOLS = Object.freeze([\n${descriptors}\n]);\n`;
}

async function writeGeneratedFile(
    root: string,
    relativePath: string,
    content: string,
    check: boolean,
) {
    const filePath = path.join(root, relativePath);
    const existing = await readFile(filePath, 'utf8').catch(() => null);
    if (existing === content) {
        return false;
    }
    if (check) {
        throw new Error(`${relativePath} is stale. Run node --import tsx scripts/generateNativeToolProtocols.ts.`);
    }
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, content, 'utf8');
    return true;
}

export async function generateNativeToolProtocols(
    options: IGenerateNativeToolProtocolsOptions = {},
) {
    const root = options.projectRoot ?? projectRoot;
    const protocols = options.protocols ?? GENERATED_RUST_NATIVE_TOOL_PROTOCOLS;
    const check = options.check ?? false;
    const changed = await Promise.all([
        writeGeneratedFile(
            root,
            generatedRustRelativePath,
            renderRustNativeToolProtocols(protocols),
            check,
        ),
        writeGeneratedFile(
            root,
            generatedReleaseRelativePath,
            renderReleaseNativeToolProtocols(protocols),
            check,
        ),
    ]);
    return changed.some(Boolean);
}

const isDirectCliRun = process.argv[1] !== undefined
    && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));

if (isDirectCliRun) {
    try {
        const changed = await generateNativeToolProtocols({ check: process.argv.includes('--check') });
        if (changed) {
            console.info('Generated native tool protocol artifacts.');
        }
    } catch (error) {
        console.error(error instanceof Error ? error.message : String(error));
        process.exitCode = 1;
    }
}
