import type * as WorkspaceOrchestration from '@app/modules/workspace-shell/types/workspaceOrchestration.types';

export type TPageAnnotationActionsPdfViewer = Pick<WorkspaceOrchestration.IPdfViewerExpose,
    'cancelCommentPlacement'
    | 'commentAtPoint'
    | 'commentSelection'
    | 'deleteAnnotationComment'
    | 'deleteSelectedShape'
    | 'focusAnnotationComment'
    | 'getSelectedShape'
    | 'getSelectedTextMarkupAnnotationProperties'
    | 'getViewerContainer'
    | 'highlightSelection'
    | 'invalidatePages'
    | 'removeAnnotationFromDom'
    | 'removeAnnotationFromInternalCache'
    | 'runSaveTransaction'
    | 'selectedShapeId'
    | 'startCommentPlacement'
    | 'startImagePlacement'
    | 'suppressAnnotationId'
    | 'suppressAnnotationStableKey'
    | 'updateAnnotationComment'
    | 'updateSelectedTextMarkupAnnotationColor'
    | 'updateTextMarkupAnnotationColor'
    | 'updateShape'
> & Partial<Pick<WorkspaceOrchestration.IPdfViewerExpose,
    'registerAnnotationHistoryCommand'
    | 'clearPendingImagePlacement'
    | 'restorePendingImagePlacement'
    | 'restoreAnnotationToInternalCache'
    | 'unsuppressAnnotationId'
    | 'unsuppressAnnotationStableKey'
>>;
