export const DEFERRED_WORKSPACE_HOST_POLICY = {
    RECENT_OPEN_LOG_SECTION: 'recent-open',
    LOADER_LOG_SECTION: 'loader',
    DOCUMENT_OPEN_SETTLE_TIMEOUT_MS: 4_000,
    WORKSPACE_MOUNT_POLL_INTERVAL_MS: 25,
    WORKSPACE_MOUNT_TIMEOUT_MS: 30_000,
    WORKSPACE_MOUNT_RETRY_TIMEOUT_MS: 20_000,
} as const;
