import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
    beforeEach,
    describe,
    expect,
    it,
} from 'vitest';
import {
    isWindowsTestResult,
    WINDOWS_TEST_RUNNER_VERSION,
    WINDOWS_TEST_SCHEMA_VERSION,
    type IWindowsTestJob,
} from '@scripts/windows-test/contracts/windowsTestContracts';
import type { IWindowsFixtureManifest } from '@scripts/windows-test/fixtures/fixtureManifest';
import {
    guestLayoutForRoot,
    guestRunPaths,
    joinGuestPath,
} from '@scripts/windows-test/guest/guestPaths';
import {
    createNodeGuestFileSystem,
    sha256Hex,
    sha256HexOfText,
    type IGuestClock,
    type IGuestCommandRunner,
} from '@scripts/windows-test/guest/guestRuntime';
import type { INativeUiAdapter } from '@scripts/windows-test/guest/native-ui/nativeUiAdapter';
import type { IViewerFactory } from '@scripts/windows-test/guest/viewer/viewerDriver';
import type { ICaseDefinition } from '@scripts/windows-test/guest/cases/caseContext';
import {
    buildWorkerResult,
    fixtureLookup,
    runGuestWorker,
    selectReadyMarker,
    sentinelPlatform,
    sentinelWorkerIdentity,
    SENTINEL_SHA256,
    SENTINEL_VM_ID,
    type IGuestWorkerAdapters,
} from '@scripts/windows-test/guest/guestWorker';

const runId = '20260904T120000Z-0123456789ab';
const vmId = '11111111-2222-4333-8444-555555555555';
const sourceSha = 'b'.repeat(40);
const artifactContents = 'installer-bytes';
const bootId = 'boot-42';
const guestTestMarker = 'evb-test-clone';
const imageId = 'win11-arm64-pro-25h2-baseline-001';
const fs = createNodeGuestFileSystem();

const fixtureManifest: IWindowsFixtureManifest = {
    schemaVersion: WINDOWS_TEST_SCHEMA_VERSION,
    packs: [{
        id: 'F01',
        name: 'Numbered pages',
        purpose: 'Twelve numbered pages used by the save and print cases.',
        license: 'synthetic',
        publishable: true,
        provenance: 'generated by the windows-test fixture builders',
        variants: [],
        metadata: {},
        files: [{
            id: 'F01-numbered-12p',
            path: 'fixtures/windows/F01/F01-numbered-12p.pdf',
            bytes: 1024,
            sha256: 'a'.repeat(64),
            expectedPages: 12,
            markers: ['EVB-F01-PAGE-01'],
            generated: true,
        }],
    }],
};

const manifestContents = JSON.stringify(fixtureManifest);

function probePayload(overrides: Record<string, unknown> = {}) {
    return {
        userSid: 'S-1-5-21-1-2-3-1001',
        sessionId: 2,
        integrityLevel: 'Medium',
        inputDesktop: 'Default',
        logonUiPresent: false,
        workerPid: 4321,
        workerStartTime: '2026-09-04T12:00:00.0000000Z',
        osVersion: '10.0.26100',
        osArchitecture: 'ARM64',
        hostname: 'EVB-TEST-VM',
        appVersion: '1.4.2',
        ...overrides,
    };
}

function fakePeImage(machine: number) {
    const bytes = new Uint8Array(0x100);
    const view = new DataView(bytes.buffer);
    bytes[0] = 0x4d;
    bytes[1] = 0x5a;
    view.setUint32(0x3c, 0x80, true);
    view.setUint32(0x80, 0x0000_4550, true);
    view.setUint16(0x84, machine, true);
    return bytes;
}

function buildJob(overrides: Partial<IWindowsTestJob> = {}): IWindowsTestJob {
    return {
        schemaVersion: WINDOWS_TEST_SCHEMA_VERSION,
        runId,
        sourceSha,
        artifactSha256: sha256HexOfText(artifactContents),
        artifactFileName: 'EVB-Viewer-Setup-arm64.exe',
        imageId,
        vmId,
        bootId,
        guestTestMarker,
        runnerVersion: WINDOWS_TEST_RUNNER_VERSION,
        suite: 'critical',
        tests: [
            'WIN-SAVE-01',
            'WIN-PRINT-01',
        ],
        fixtureManifestSha256: sha256HexOfText(manifestContents),
        expectedOsArch: 'arm64',
        expectedAppArch: 'arm64',
        deadlineSeconds: 900,
        ...overrides,
    };
}

const refusingAdapters: IGuestWorkerAdapters = {
    createNativeUiAdapter: () => new Proxy({}, { get: () => () => {
        throw new Error('the native UI adapter must not be used by this test');
    } }) as INativeUiAdapter,
    createViewerFactory: () => new Proxy({}, { get: () => () => {
        throw new Error('the viewer factory must not be used by this test');
    } }) as IViewerFactory,
};

function fakeCase(id: string, run: ICaseDefinition['run']): ICaseDefinition {
    return {
        id,
        family: 'save',
        driver: 'APP',
        ledgerDrivers: 'APP',
        actionKind: 'app',
        status: 'implemented',
        run,
    };
}

function passingCase(id: string, executed: string[]) {
    return fakeCase(id, (context) => {
        executed.push(id);
        context.assert(`${id}.ran`, true, 'the fake case recorded an assertion');
        return Promise.resolve();
    });
}

interface IStageOptions {
    job?: IWindowsTestJob | null;
    jobText?: string;
    probe?: Record<string, unknown>;
    machine?: number;
    writeReadyMarker?: boolean;
    cancelBeforeTest?: string;
}

let root = '';

async function stageGuest(options: IStageOptions = {}) {
    const layout = guestLayoutForRoot(root, '/');
    const paths = guestRunPaths(layout, runId);
    const executablePath = joinGuestPath('/', root, 'app', 'EVB Viewer.exe');
    await fs.writeText(layout.bootIdFile, `${bootId}\n`);
    await fs.writeText(layout.markerFile, JSON.stringify({
        guestTestMarker,
        imageId,
    }));
    await fs.writeText(joinGuestPath('/', paths.stagingDir, 'EVB-Viewer-Setup-arm64.exe'), artifactContents);
    await fs.writeText(paths.fixtureManifestFile, manifestContents);
    await fs.writeBytes(executablePath, fakePeImage(options.machine ?? 0xaa64));
    const jobText = options.jobText ?? JSON.stringify(options.job === undefined ? buildJob() : options.job);
    await fs.writeText(paths.jobFile, jobText);
    if (options.writeReadyMarker !== false) {
        await fs.writeText(paths.readyMarkerFile, '');
    }
    return {
        layout,
        paths,
        executablePath,
    };
}

function stubClock(): IGuestClock {
    let currentTime = 1_700_000_000_000;
    return {
        now: () => currentTime,
        nowIso: () => new Date(currentTime).toISOString(),
        sleep: (milliseconds) => {
            currentTime += milliseconds;
            return Promise.resolve();
        },
    };
}

function stubExec(
    probe: Record<string, unknown>,
    onInstall = () => undefined,
    onProbe = () => undefined,
): IGuestCommandRunner {
    return { run: (command, args) => {
        if (args.some(argument => argument.endsWith('probe-identity.ps1'))) {
            onProbe();
            return Promise.resolve({
                exitCode: 0,
                stdout: JSON.stringify(probe),
                stderr: '',
            });
        }
        if (args.some(argument => argument.endsWith('install-nsis-per-user.ps1'))) {
            onInstall();
            return Promise.resolve({
                exitCode: 0,
                stdout: JSON.stringify({installed: true}),
                stderr: '',
            });
        }
        return Promise.reject(new Error(`unexpected command ${command} ${args.join(' ')}`));
    } };
}

describe('guest worker mailbox loop', () => {
    beforeEach(async () => {
        root = await mkdtemp(path.join(tmpdir(), 'evb-guest-worker-'));
    });

    it('picks the oldest ready marker and ignores unrelated inbox names', () => {
        expect(selectReadyMarker([
            'notes.txt',
            '20260904T130000Z-0123456789ab.ready',
            '20260904T120000Z-0123456789ab.ready',
            '20260904T120000Z-0123456789ab.job.json',
        ])).toBe('20260904T120000Z-0123456789ab');
        expect(selectReadyMarker([])).toBeNull();
        expect(selectReadyMarker(['not-a-run-id.ready'])).toBeNull();
    });

    it('resolves staged fixtures by id and refuses unknown ids', () => {
        const lookup = fixtureLookup(fixtureManifest, 'C:\\evb-test\\staging\\fixtures', '\\');
        expect(lookup('F01-numbered-12p')).toBe('C:\\evb-test\\staging\\fixtures\\F01-numbered-12p.pdf');
        expect(() => lookup('F09-missing')).toThrow('has no entry for F09-missing');
    });

    it('exposes sentinels that keep a rejection result schema valid', () => {
        expect(SENTINEL_VM_ID).toBe('00000000-0000-4000-8000-000000000000');
        expect(SENTINEL_SHA256).toHaveLength(64);
        expect(sentinelWorkerIdentity(11, '2026-09-04T12:00:00Z').interactive).toBe(false);
        expect(sentinelPlatform('arm64').osArch).toBe('arm64');
    });

    it('returns without a result when no ready marker ever appears', async () => {
        const staged = await stageGuest({writeReadyMarker: false});
        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload()),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            heartbeatIntervalMs: 0,
        });

        expect(summary).toEqual({
            result: null,
            resultFile: null,
            reason: 'no ready marker appeared in the guest inbox',
        });
        expect(await fs.exists(staged.paths.resultFile)).toBe(false);
    });

    it('refreshes the idle identity until a desktop that was initially locked becomes usable', async () => {
        const staged = await stageGuest({
            job: buildJob({tests: ['WIN-SAVE-01']}),
            writeReadyMarker: false,
        });
        await fs.remove(staged.paths.readyMarkerFile);
        let probeCalls = 0;
        const exec: IGuestCommandRunner = {run: (command, args) => {
            if (args.some(argument => argument.endsWith('probe-identity.ps1'))) {
                probeCalls += 1;
                return Promise.resolve({
                    exitCode: 0,
                    stdout: JSON.stringify(probePayload({logonUiPresent: probeCalls === 1})),
                    stderr: '',
                });
            }
            if (args.some(argument => argument.endsWith('install-nsis-per-user.ps1'))) {
                return Promise.resolve({
                    exitCode: 0,
                    stdout: JSON.stringify({installed: true}),
                    stderr: '',
                });
            }
            return Promise.reject(new Error(`unexpected command ${command} ${args.join(' ')}`));
        }};
        const originalListNames = fs.listNames;
        let listCalls = 0;
        const delayedReadyFs = {
            ...fs,
            listNames: async (directoryPath: string) => {
                listCalls += 1;
                if (listCalls === 2) {
                    await fs.writeText(staged.paths.readyMarkerFile, '');
                }
                return originalListNames(directoryPath);
            },
        };

        const summary = await runGuestWorker({
            fs: delayedReadyFs,
            exec,
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            caseDefinitions: [passingCase('WIN-SAVE-01', [])],
            waitForJobMs: 5_000,
            pollIntervalMs: 10,
            heartbeatIntervalMs: 0,
        });

        expect(probeCalls).toBeGreaterThan(1);
        expect(summary.result?.outcome).toBe('passed');
        expect(summary.result?.worker.interactive).toBe(true);
    });

    it('throttles idle identity probes to the heartbeat interval', async () => {
        const staged = await stageGuest({writeReadyMarker: false});
        let probeCalls = 0;
        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload(), () => undefined, () => {
                probeCalls += 1;
            }),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: {EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath},
            waitForJobMs: 50,
            pollIntervalMs: 10,
            heartbeatIntervalMs: 20,
        });

        expect(summary.result).toBeNull();
        expect(probeCalls).toBeGreaterThan(1);
        expect(probeCalls).toBeLessThanOrEqual(3);
    });

    it('writes a schema-valid infrastructure-failed result when the job is rejected', async () => {
        const staged = await stageGuest({ job: buildJob({ bootId: 'boot-99' }) });
        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload()),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            heartbeatIntervalMs: 0,
        });

        expect(summary.result?.outcome).toBe('infrastructure-failed');
        expect(summary.reason).toContain('boot');
        const written: unknown = JSON.parse(await fs.readText(staged.paths.resultFile));
        expect(isWindowsTestResult(written)).toBe(true);
        expect(await fs.exists(staged.paths.resultTempFile)).toBe(false);
        expect(await fs.exists(staged.paths.startedMarkerFile)).toBe(false);
    });

    it('writes a rejection result even when the job file is not JSON', async () => {
        const staged = await stageGuest({ jobText: 'this is not json' });
        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload()),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            heartbeatIntervalMs: 0,
        });

        expect(summary.result?.vmId).toBe(SENTINEL_VM_ID);
        expect(summary.result?.artifactSha256).toBe(SENTINEL_SHA256);
        expect(summary.reason).toContain('missing or not JSON');
        expect(isWindowsTestResult(JSON.parse(await fs.readText(staged.paths.resultFile)))).toBe(true);
    });

    it('refuses a duplicate run without replacing its prior diagnostics', async () => {
        const staged = await stageGuest();
        const priorLog = 'prior worker log from the crashed attempt\n';
        const priorEvidence = 'prior diagnostic evidence\n';
        const priorManifest = `${JSON.stringify({
            schemaVersion: WINDOWS_TEST_SCHEMA_VERSION,
            runId,
            entries: [{
                relativePath: 'prior.txt',
                sha256: sha256HexOfText(priorEvidence),
                bytes: priorEvidence.length,
            }],
        }, null, 4)}\n`;
        const priorResult = `${JSON.stringify(buildWorkerResult({
            runId,
            job: buildJob(),
            outcome: 'infrastructure-failed',
            startedAt: '2026-09-04T12:00:01.000Z',
            endedAt: '2026-09-04T12:00:02.000Z',
            cases: [],
            worker: sentinelWorkerIdentity(9_876, '2026-09-04T12:00:01.000Z'),
            platform: sentinelPlatform('arm64'),
            evidenceManifestSha256: 'a'.repeat(64),
            logTruncated: false,
            humanReviewRequired: true,
            failureReason: 'prior crash',
        }), null, 4)}\n`;
        expect(isWindowsTestResult(JSON.parse(priorResult))).toBe(true);
        await fs.writeText(staged.paths.startedMarkerFile, '2026-09-04T12:00:01.000Z\n');
        await fs.writeText(staged.paths.workerLogFile, priorLog);
        await fs.writeText(staged.paths.evidenceManifestFile, priorManifest);
        await fs.writeText(staged.paths.resultFile, priorResult);
        await fs.writeText(joinGuestPath('/', staged.paths.evidenceDir, 'prior.txt'), priorEvidence);
        const executed: string[] = [];
        let installCalls = 0;

        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload(), () => {
                installCalls += 1;
            }),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            caseDefinitions: [passingCase('WIN-SAVE-01', executed)],
            heartbeatIntervalMs: 0,
        });

        expect(summary.result).toBeNull();
        expect(summary.resultFile).toBeNull();
        expect(summary.reason).toContain('duplicate execution refused');
        expect(installCalls).toBe(0);
        expect(executed).toEqual([]);
        expect(await fs.readText(staged.paths.startedMarkerFile)).toBe('2026-09-04T12:00:01.000Z\n');
        expect(await fs.readText(staged.paths.workerLogFile)).toBe(priorLog);
        expect(await fs.readText(staged.paths.evidenceManifestFile)).toBe(priorManifest);
        expect(await fs.readText(staged.paths.resultFile)).toBe(priorResult);
        expect(await fs.readText(joinGuestPath('/', staged.paths.evidenceDir, 'prior.txt'))).toBe(priorEvidence);
        expect(await fs.exists(staged.paths.resultTempFile)).toBe(false);
    });

    it('refuses malformed input when a prior result exists without a started marker', async () => {
        const staged = await stageGuest({ jobText: 'this is not json' });
        const priorLog = 'prior log bytes\n';
        const priorManifest = 'prior manifest bytes\n';
        const priorResult = 'prior result bytes\n';
        const priorEvidence = 'prior evidence bytes\n';
        await fs.writeText(staged.paths.workerLogFile, priorLog);
        await fs.writeText(staged.paths.evidenceManifestFile, priorManifest);
        await fs.writeText(staged.paths.resultFile, priorResult);
        await fs.writeText(joinGuestPath('/', staged.paths.evidenceDir, 'prior.txt'), priorEvidence);
        const executed: string[] = [];
        let installCalls = 0;

        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload(), () => {
                installCalls += 1;
            }),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            caseDefinitions: [passingCase('WIN-SAVE-01', executed)],
            heartbeatIntervalMs: 0,
        });

        expect(summary.result).toBeNull();
        expect(summary.resultFile).toBeNull();
        expect(summary.reason).toContain('prior output');
        expect(installCalls).toBe(0);
        expect(executed).toEqual([]);
        expect(await fs.exists(staged.paths.startedMarkerFile)).toBe(false);
        expect(await fs.readText(staged.paths.workerLogFile)).toBe(priorLog);
        expect(await fs.readText(staged.paths.evidenceManifestFile)).toBe(priorManifest);
        expect(await fs.readText(staged.paths.resultFile)).toBe(priorResult);
        expect(await fs.readText(joinGuestPath('/', staged.paths.evidenceDir, 'prior.txt'))).toBe(priorEvidence);
        expect(await fs.exists(staged.paths.resultTempFile)).toBe(false);
    });

    it('refuses to run cases from a Session 0 worker (I9)', async () => {
        const staged = await stageGuest();
        const executed: string[] = [];
        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload({ sessionId: 0 })),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            caseDefinitions: [passingCase('WIN-SAVE-01', executed)],
            heartbeatIntervalMs: 0,
        });

        expect(summary.result?.outcome).toBe('infrastructure-failed');
        expect(summary.reason).toContain('Session 0');
        expect(summary.result?.worker.interactive).toBe(false);
        expect(summary.result?.executedTests).toEqual([]);
        expect(executed).toEqual([]);
    });

    it('refuses a locked session and an input desktop that is not Default (I9)', async () => {
        const staged = await stageGuest();
        let installCalls = 0;
        const locked = await runGuestWorker({
            fs,
            exec: stubExec(probePayload({logonUiPresent: true}), () => {
                installCalls += 1;
            }),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            heartbeatIntervalMs: 0,
        });

        expect(locked.reason).toContain('locked');
        expect(installCalls).toBe(0);
    });

    it('refuses an installed executable that is not the expected architecture', async () => {
        const staged = await stageGuest({ machine: 0x8664 });
        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload()),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            heartbeatIntervalMs: 0,
        });

        expect(summary.result?.outcome).toBe('infrastructure-failed');
        expect(summary.reason).toContain('the installed executable was rejected');
        expect(summary.result?.platform.installedExecutableSha256).toBe(SENTINEL_SHA256);
    });

    it('runs the requested cases in order and writes the result atomically', async () => {
        const staged = await stageGuest();
        const executed: string[] = [];
        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload()),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            caseDefinitions: [
                passingCase('WIN-PRINT-01', executed),
                passingCase('WIN-SAVE-01', executed),
            ],
            heartbeatIntervalMs: 0,
        });

        expect(executed).toEqual([
            'WIN-SAVE-01',
            'WIN-PRINT-01',
        ]);
        expect(summary.result?.outcome).toBe('passed');
        expect(summary.result?.executedTests).toEqual([
            'WIN-SAVE-01',
            'WIN-PRINT-01',
        ]);
        expect(summary.result?.assertionCount).toBe(2);
        expect(summary.result?.failedAssertionCount).toBe(0);
        expect(summary.result?.platform).toMatchObject({
            osArch: 'arm64',
            appArch: 'arm64',
            appVersion: '1.4.2',
            installedExecutableSha256: sha256Hex(fakePeImage(0xaa64)),
        });
        expect(summary.result?.humanReviewRequired).toBe(true);
        expect(summary.resultFile).toBe(staged.paths.resultFile);
        expect(await fs.exists(staged.paths.resultTempFile)).toBe(false);
        expect(isWindowsTestResult(JSON.parse(await fs.readText(staged.paths.resultFile)))).toBe(true);
        expect(await fs.exists(staged.paths.startedMarkerFile)).toBe(true);
        expect(await fs.exists(staged.paths.evidenceManifestFile)).toBe(true);
        expect(await fs.readText(staged.paths.workerLogFile)).toContain('running WIN-SAVE-01');
    });

    it('keeps a heartbeat with the worker pid, boot id and last state', async () => {
        const staged = await stageGuest();
        const executed: string[] = [];
        await runGuestWorker({
            fs,
            exec: stubExec(probePayload()),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            workerPid: 9_876,
            caseDefinitions: [
                passingCase('WIN-SAVE-01', executed),
                passingCase('WIN-PRINT-01', executed),
            ],
            heartbeatIntervalMs: 0,
        });

        const heartbeat: unknown = JSON.parse(await fs.readText(staged.layout.heartbeatFile));
        expect(heartbeat).toMatchObject({
            schemaVersion: WINDOWS_TEST_SCHEMA_VERSION,
            bootId,
            guestTestMarker,
            locked: false,
            worker: {
                workerPid: 4321,
                workerStartTime: '2026-09-04T12:00:00.0000000Z',
            },
            lastState: 'complete',
        });
    });

    it('stops between cases when the host drops a cancel file', async () => {
        const staged = await stageGuest();
        const executed: string[] = [];
        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload()),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            caseDefinitions: [
                fakeCase('WIN-SAVE-01', async (context) => {
                    executed.push('WIN-SAVE-01');
                    context.assert('cancel.first-case-ran', true, 'the first case finished before the cancel');
                    await fs.writeText(staged.paths.cancelFile, 'stop');
                }),
                passingCase('WIN-PRINT-01', executed),
            ],
            heartbeatIntervalMs: 0,
        });

        expect(executed).toEqual(['WIN-SAVE-01']);
        expect(summary.result?.outcome).toBe('canceled');
        expect(summary.reason).toContain('canceled before WIN-PRINT-01');
        expect(summary.result?.executedTests).toEqual(['WIN-SAVE-01']);
    });

    it('stops between cases when the job deadline expires', async () => {
        const staged = await stageGuest({ job: buildJob({ deadlineSeconds: 60 }) });
        const executed: string[] = [];
        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload()),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            caseDefinitions: [
                fakeCase('WIN-SAVE-01', async (context) => {
                    executed.push('WIN-SAVE-01');
                    context.assert('deadline.first-case-ran', true, 'the first case finished inside the deadline');
                    await context.clock.sleep(120_000);
                }),
                passingCase('WIN-PRINT-01', executed),
            ],
            heartbeatIntervalMs: 0,
        });

        expect(executed).toEqual(['WIN-SAVE-01']);
        expect(summary.result?.outcome).toBe('infrastructure-failed');
        expect(summary.reason).toContain('deadline of 60s expired before WIN-PRINT-01');
    });

    it('marks a test the registry does not know as unsupported instead of failing the run', async () => {
        const staged = await stageGuest({ job: buildJob({ tests: ['WIN-NOPE-99'] }) });
        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload()),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            caseDefinitions: [],
            heartbeatIntervalMs: 0,
        });

        expect(summary.result?.outcome).toBe('unsupported');
        expect(summary.result?.cases[0]).toMatchObject({
            testId: 'WIN-NOPE-99',
            outcome: 'unsupported',
        });
        expect(summary.result?.humanReviewRequired).toBe(true);
    });

    it('reports a case that never asserts as unsupported rather than passed', async () => {
        const staged = await stageGuest({ job: buildJob({ tests: ['WIN-SAVE-01'] }) });
        const summary = await runGuestWorker({
            fs,
            exec: stubExec(probePayload()),
            clock: stubClock(),
            paths: staged.layout,
            adapters: refusingAdapters,
            env: { EVB_WINDOWS_TEST_APP_EXECUTABLE: staged.executablePath },
            caseDefinitions: [fakeCase('WIN-SAVE-01', () => Promise.resolve())],
            heartbeatIntervalMs: 0,
        });

        expect(summary.result?.outcome).toBe('unsupported');
        expect(summary.result?.assertionCount).toBe(0);
        expect(summary.result?.cases[0]?.failureReason).toContain('without recording a single assertion');
    });
});
