// Generated by scripts/generateNativeToolProtocols.ts. Do not edit.

use crate::NativeToolDescriptor;

pub const PDF_IMAGE_COMBINE: NativeToolDescriptor =
    NativeToolDescriptor::new("evb-pdf-image-combine", 4);

pub const PDF_PAGE_OPS: NativeToolDescriptor = NativeToolDescriptor::new("evb-pdf-page-ops", 1);

pub const PDF_SEARCH: NativeToolDescriptor = NativeToolDescriptor::new("evb-pdf-search", 1);

pub const SCAN_CLEANUP: NativeToolDescriptor = NativeToolDescriptor::new("evb-scan-cleanup", 7);

pub const ALL_NATIVE_TOOL_DESCRIPTORS: &[NativeToolDescriptor] =
    &[PDF_IMAGE_COMBINE, PDF_PAGE_OPS, PDF_SEARCH, SCAN_CLEANUP];
