export {
    CANVAS_CONTENT_SCALE_EPSILON,
    orientScanCleanupInsetsToPageSpace,
    resolveMatchedCanvasResamplePages,
    resolveScanCleanupCanvasFitScale,
    resolveScanCleanupDocumentCanvasDpi,
    resolveScanCleanupDocumentCanvasRenderDpi,
    resolveScanCleanupDocumentCanvas,
    resolveScanCleanupProvisionalDocumentCanvas,
    resolveScanCleanupDroppedMatchWarning,
    resolveScanCleanupPageCanvasBox,
    resolveScanCleanupOutputPageRect,
    resolveScanCleanupOutputPageSpacePaperRect,
    resolveScanCleanupOutputPaperPixels,
    resolveScanCleanupUnclassifiedPages,
    SCAN_CLEANUP_LOSSLESS_CANVAS_GRID_DPI,
} from '@scan-cleanup-core/policy/documentCanvas';
