export {
    detectArchitecture,
    detectPlatform,
    compareInstallersForSelect,
    formatArch,
    formatExtension,
    formatFileSize,
    formatInstallerLabel,
    formatInstallerVariantLabel,
    formatPlatform,
    getAssetExtension,
    INSTALLER_PLATFORM_ORDER,
    isInstallerAsset,
    isLegacyInstallerAsset,
    normalizeInstallers,
    parseArchitectureHint,
    parsePlatformHint,
    parseUserAgent,
    recommendInstaller,
    selectPreferredInstallers,
} from './releaseSelection';

export type {
    ILatestReleaseResponse,
    IReleaseInstaller,
    IReleaseSummary,
    IUserAgentProfile,
    TReleaseArch,
    TReleasePlatform,
} from '@contracts';
