export type TToolbarAppMenuCommand =
    | 'open-file'
    | 'save'
    | 'repair-save'
    | 'optimize-pdf-for-interaction'
    | 'save-as'
    | 'print'
    | 'print-current-page'
    | 'combine-images'
    | 'export-docx'
    | 'export-images'
    | 'export-multi-page-tiff'
    | 'convert-to-pdf'
    | 'undo'
    | 'redo'
    | 'insert-image-from-file'
    | 'paste-image-from-clipboard';

export type TToolbarOverflowMenuCommand =
    | 'open-ocr'
    | 'toggle-sidebar'
    | 'fit-width'
    | 'fit-height'
    | 'enable-drag'
    | 'disable-drag'
    | 'toggle-continuous-scroll'
    | 'capture-region'
    | 'crop'
    | 'quick-note'
    | 'toggle-fullscreen'
    | 'open-settings'
    | 'combine-images'
    | 'print-current-page'
    | 'convert-to-pdf';
